name: silk-swarakarna-uas
type: php
docroot: public
php_version: "8.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
database:
  type: mariadb
  version: "10.11"
  createdb_name: silk_swarakarna
  pub_port: "3306"
composer_version: "2"
nodejs_version: "20"
web_environment:
  - DB_HOST=db
  - DB_PORT=3306
  - DB_NAME=silk_swarakarna
  - DB_USER=db
  - DB_PASS=db
  - APP_URL=${DDEV_PRIMARY_URL}
  - APP_DEBUG=true
additional_hostnames: []
additional_fqdns: []
use_dns_when_possible: true
mute_web_container: false
project_tld: ""
